apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.shellOperator.mutatingWebhookServiceName }}
  labels:
    heritage: example-205
spec:
#  type: LoadBalancer
#  externalTrafficPolicy: Local
  ports:
    - name: mutating-webhook
      port: 443
      targetPort: 9680
      protocol: TCP
  selector:
    app: shell-operator-example-205
